kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: haskell:9.0.1-buster
    commands:
      - cabal build

  - name: test
    image: haskell:9.0.1-buster
    commands:
      - cabal test --test-show-details=direct --test-option=--format=progress
